### ISSUE TITLE
Delete assets is not working

### ISSUE THREAD

**Issue by roberto-butti** [RicLeP/laravel-storyblok-previews#1]
https://github.com/RicLeP/laravel-storyblok-previews/blob/71760f52641aa229689d65440a818df6ddaba840/src/Console/CreateBlockPreviewsCommand.php#L251

@RicLeP  A suggestion here, try to replace '/spaces/' with 'spaces/'

**Comment by RicLeP** [comment]
That’s fixed it, thank you! I’ll make a new release soon.
